build:
  image: ghcr.io/cofob/node-hugo-jq
  script:
    - |
      hugo
      ipfs-car --wrapWithDirectory false --pack public/
      export CID=`curl -X 'POST' \
        'https://api.web3.storage/car' \
        -H 'accept: application/json' \
        -H "Authorization: Bearer $JWT" \
        -H 'Content-Type: application/vnd.ipld.car' \
        --data-binary '@public.car' | jq -r .cid`
      echo https://i.frsqr.xyz/ipfs/$CID
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - docker
